# Generated by Django 5.0.7 on 2024-10-29 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_slno_blogcomment_sno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='Sno',
            new_name='sno',
        ),
    ]
