# Generated by Django 5.0.7 on 2024-10-29 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_sno_blogcomment_sno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='sno',
            new_name='slno',
        ),
    ]
