# Generated by Django 5.0.7 on 2024-10-29 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_comment_blogcomment_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='content',
            new_name='comment',
        ),
    ]
